import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import{Mail,Lock,ArrowRight,Eye,EyeOff,LogOut,Building2}from'lucide-react';import'./style.css';
const rawUrl=import.meta.env.VITE_SUPABASE_URL;const url=rawUrl?.replace(/\/rest\/v1\/?$/,'').replace(/\/$/,'');const key=import.meta.env.VITE_SUPABASE_ANON_KEY;const supabase=url&&key?createClient(url,key):null;
function App(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[showPassword,setShowPassword]=useState(false);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[session,setSession]=useState(null);const[loadingSession,setLoadingSession]=useState(true);
useEffect(()=>{if(!supabase){setLoadingSession(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setLoadingSession(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,nextSession)=>{setSession(nextSession||null)});return()=>subscription.unsubscribe()},[]);
async function login(e){e.preventDefault();if(!supabase){setMsg('Configuração do banco não encontrada.');return}setBusy(true);setMsg('');const{data,error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error){setMsg('Não foi possível entrar. Verifique o e-mail e a senha.');return}setSession(data.session);setMsg('')}
async function logout(){if(!supabase)return;setBusy(true);await supabase.auth.signOut();setSession(null);setBusy(false)}
if(loadingSession)return <main className="loading-page">Carregando...</main>;
if(session)return <main className="app-shell"><header className="app-header"><div className="app-brand"><img src="/pem-condominios-logo.jpg" alt="PEM Condomínios"/><div><strong>PEM Condomínios</strong><span>Gestão Condominial Inteligente</span></div></div><button className="logout-btn" onClick={logout} disabled={busy}><LogOut size={18}/>Sair</button></header><section className="dashboard"><div className="welcome"><span>PAINEL INTERNO</span><h1>Bem-vindo ao PEM Condomínios</h1><p>Login realizado com sucesso. Você já está dentro do ambiente administrativo.</p></div><div className="dashboard-card"><Building2 size={30}/><div><strong>Área administrativa ativa</strong><p>Conta conectada: {session.user?.email}</p></div></div></section></main>;
return <main className="page"><section className="brand"><img className="brand-logo" src="/pem-condominios-logo.jpg" alt="PEM Condomínios - Gestão Condominial Inteligente"/></section><section className="card"><div className="intro"><span>GESTÃO CONDOMINIAL</span><h2>Bem-vindo</h2><p>Administração organizada, informação clara e controle em um só lugar.</p></div><form onSubmit={login}><label>E-mail<div className="field"><Mail size={18}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com" required/></div></label><label>Senha<div className="field"><Lock size={18}/><input type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required/><button type="button" className="password-toggle" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Ocultar senha':'Mostrar senha'} title={showPassword?'Ocultar senha':'Mostrar senha'}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><button type="submit" disabled={busy}>{busy?'Entrando...':'Entrar'}<ArrowRight size={18}/></button>{msg&&<div className="msg">{msg}</div>}</form><small>PEM Condomínios · Gestão Condominial Inteligente</small></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
